### PR TITLE
Some fixes

### LINKED ISSUE #22: add debug logging for request batches, sending to kafka

### LINKED ISSUE #23: extract incoming request client ip from custom header
- instead of request peer_addr, ip should be extracted from header;
- header name should be provided via the config (ip_header), similarly to host_header

### LINKED ISSUE #24: add timestamp to request
add timestamp to request before adding it to batch for sending to kafka

### PR DESCRIPTION
**Pull request by lynxbyorion**
Closed #24 
Closed #23 
Closed #22

### CODE REVIEW

File: src/service/request.rs [hunk 1]
```diff
@@ -16,22 +20,36 @@ pub struct Request {
...
-        host_header: &str,
+        request_config: RequestConfig,
         request: HttpRequest,
         body: web::Bytes,
     ) -> anyhow::Result<Request> {
         let req = Request {
-            remote_ip: match request.peer_addr() {
-                Some(n) => n.ip().to_string(),
-                None => String::new(),
+            timestamp: match SystemTime::now().duration_since(SystemTime::UNIX_EPOCH) {
```
Comment (stuffy-idler) [inline src/service/request.rs:28]: I suggest to use crate `chrono` and its `DateTime::<Utc>` instead of `SystemTime` to have timezone-less timestamp

File: src/server/http.rs [hunk 2]
```diff
@@ -47,7 +47,7 @@ async fn default_handler(
         return Ok(HttpResponse::NoContent().body(""));
     }
 
-    let req = match Request::new(&state.config.service.host_header, req, body) {
+    let req = match Request::new(state.config.service.request.clone(), req, body) {
```
Comment (stuffy-idler) [inline src/server/http.rs:50]: Is it needed in cloned config, not a ref?

**Review by stuffy-idler — CHANGES_REQUESTED** [review]

**Review by stuffy-idler — APPROVED** [review]
