### PR TITLE
26 improve error logging

### LINKED ISSUE #26: Improve error logging
At this moment in case of failed request handling, e.g. incoming request does not contains one of required header, it prints error log in `src/server/http.rs` as `error!("{}: for request: {:?}", e, req);` (req is printing in multiline) and returns an error without context as `return Err(Error::InternalError);`. 
Afterward `actix_web::middleware::logger` print a debug log as `Error in response: InternalError`.
And afterward `tracing_actix_web::middleware` print an error log as `Error encountered while processing the incoming HTTP request: InternalError`.
As a result: we have 2 error and 1 debug messages, two of which does not describe an error.

Suggestion is to improve error logging: reduce messages to one, format it and provide context for it.

### PR DESCRIPTION
**Pull request by lynxbyorion**
Closed #26

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -22,7 +22,10 @@ async fn main() -> anyhow::Result<()> {
     init_tracing();
     info!("start application");
 
-    let app_config = config::AppConfig::load()?;
+    let app_config = match config::AppConfig::load() {
```
Comment (stuffy-idler) [inline src/main.rs:25]: It can be rewritten as:
```rust
let app_config = config::AppConfig::load().map_err(|e| anyhow::anyhow!("config load: {}", e))?;
```

File: src/main.rs [hunk 2]
```diff
@@ -33,7 +36,10 @@ async fn main() -> anyhow::Result<()> {
     let shutdowner = Arc::new(Shutdowner::new());
 
     let (kafka_sender, kafka_receiver) = mpsc::channel::<(String, Vec<service::Request>)>(32);
-    let mut kafka_producer = kafka::Service::new(&app_config, kafka_receiver)?;
+    let mut kafka_producer = match kafka::Service::new(&app_config, kafka_receiver) {
```
Comment (stuffy-idler) [inline src/main.rs:39]: The same note as for `app_config`

File: src/main.rs [hunk 3]
```diff
@@ -49,7 +55,10 @@ async fn main() -> anyhow::Result<()> {
         tokio::spawn(async move { service::process(store, kafka_sender, cfg, tick_tock).await })
     };
 
-    let (server, server_handle) = server::Server::run(app_config.server, metrics, data)?;
+    let (server, server_handle) = match server::Server::run(app_config.server, metrics, data) {
```
Comment (stuffy-idler) [inline src/main.rs:58]: The same note as for `app_config`

**Review by stuffy-idler — CHANGES_REQUESTED** [review]

File: src/server/http.rs [hunk 4]
```diff
@@ -61,14 +61,14 @@ async fn default_handler(
...
-        return Ok(HttpResponse::NoContent().body(""));
+        return Ok(HttpResponse::NoContent().finish());
     }
 
     let req = match Request::new(&state.config.service.request, &req, body) {
         Ok(r) => r,
         Err(e) => {
-            error!("{}: for request: {:?}", e, req);
-            return Err(Error::InternalError);
+            warn!("failed parse request: {}", e);
```
[the remark this answers is not in the document]
Comment (lynxbyorion) [reply src/server/http.rs]: fixed

File: src/main.rs (hunk 1 above)
Comment (lynxbyorion) [reply src/main.rs]: fixed

File: src/main.rs (hunk 2 above)
Comment (lynxbyorion) [reply src/main.rs]: fixed

**Review by stuffy-idler — APPROVED** [review]
